services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda123
      POSTGRES_DB: tienda_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://tienda:tienda123@db:5432/tienda_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
