"""models updated

Revision ID: 5e41c7822258
Revises: 4f80622aceb3
Create Date: 2026-07-14 00:09:17.018509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e41c7822258'
down_revision: Union[str, Sequence[str], None] = '4f80622aceb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    transactionstatus = sa.Enum('active', 'refunded', name='transactionstatus')
    transactionstatus.create(op.get_bind())
    op.add_column('transactions', sa.Column('status', transactionstatus, server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    sa.Enum(name='transactionstatus').drop(op.get_bind())
    op.drop_table('refunds')
    # ### end Alembic commands ###
